import type { Metadata } from "next";
import "./globals.css";
import KakaoScript from "./KakaoScript";

declare global {
  interface Window {
    Kakao: any;
  }
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
        <title>캐치데이트</title>
      </head>
      <body
        className={`flex items-center justify-center w-screen h-screen bg-gray-100`}
      >
        <div className="w-[375px] h-[667px] bg-white border border-gray-300 p-6 overflow-hidden">
          <KakaoScript />
          {children}
        </div>
      </body>
    </html>
  );
}
